# Generated by Django 5.0.6 on 2024-06-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('line1', models.CharField(max_length=69)),
                ('line2', models.CharField(max_length=69)),
                ('satellite_catalog_number', models.IntegerField()),
                ('classification', models.CharField(max_length=1)),
                ('launch_year', models.IntegerField()),
                ('epoch_year', models.IntegerField()),
                ('epoch', models.FloatField()),
                ('revolutions', models.IntegerField()),
                ('revolutions_per_day', models.FloatField()),
            ],
        ),
    ]
