# Generated by Django 5.0.6 on 2024-06-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satellite_app', '0003_satellite_affiliation_alter_satellite_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='satellite',
            name='id',
        ),
        migrations.AlterField(
            model_name='satellite',
            name='satellite_catalog_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
