# Generated by Django 5.0.6 on 2024-06-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satellite_app', '0004_remove_satellite_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satellite',
            name='classification',
            field=models.CharField(choices=[('U', 'Unclassified'), ('C', 'Classified'), ('S', 'Secret')], default='U', max_length=1),
        ),
    ]
