# Generated by Django 5.0.6 on 2024-06-10 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('satellite_app', '0006_minorcategory_remove_satellite_affiliation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='minorcategory',
            options={'verbose_name_plural': 'Minor Categories'},
        ),
    ]
