# Generated by Django 5.0.6 on 2024-06-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satellite_app', '0007_alter_minorcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='satellite',
            name='country',
            field=models.CharField(blank=True, default='', max_length=5),
        ),
    ]
