# Generated by Django 5.0.6 on 2024-06-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satellite_app', '0008_satellite_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satellite',
            name='country',
            field=models.CharField(blank=True, db_index=True, default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='launch_year',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='minor_categories',
            field=models.ManyToManyField(db_index=True, related_name='satellites', to='satellite_app.minorcategory'),
        ),
    ]
