# Generated by Django 5.0.6 on 2024-06-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('satellite_app', '0009_alter_satellite_country_alter_satellite_launch_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minorcategory',
            name='minor_category',
            field=models.CharField(choices=[('None', 'None'), ("Last 30 Days' Launches", 'Last 30 Days'), ('Space Stations', 'Space Stations'), ('Active Satellites', 'Active'), ('Weather', 'Weather'), ('NOAA', 'Noaa'), ('Earth Resources', 'Earth Resources'), ('Search & Rescue (SARSAT)', 'Search And Rescue'), ('Disaster Monitoring', 'Disaster Monitoring'), ('ARGOS Data Collection System', 'Argos'), ('Planet', 'Planet'), ('Spire', 'Spire'), ('Active Geosynchronous', 'Active Geosynchronous'), ('Starlink', 'Starlink'), ('Iridium', 'Iridium'), ('Intelsat', 'Intelsat'), ('Swarm', 'Swarm'), ('Amateur Radio', 'Amateur Radio'), ('GNSS', 'Gnss'), ('GPS Operational', 'Gps'), ('Glonass Operational', 'Glonass'), ('Galileo', 'Galileo'), ('Beidou', 'Beidou'), ('Space and Earth Science', 'Space And Earth'), ('Geodetics', 'Geodetics'), ('Engineering', 'Engineering')], default='None', max_length=45),
        ),
    ]
