export const countryToName = {
  US: 'United States',
  FR: 'France',
  DE: 'Germany',
  GB: 'Great Britain',
  JP: 'Japan',
  RU: 'Russia',
  AR: 'Argentina',
  IT: 'Italy',
  BR: 'Brazil',
  INT: 'International',
  CN: 'China',
  LU: 'Luxembourg',
  IL: 'Israel',
  EU: 'European Union',
  CA: 'Canada',
  SE: 'Sweden',
  SA: 'Saudi Arabia',
  GR: 'Greece',
  AE: 'United Arab Emirates',
  AU: 'Australia',
  IN: 'India',
  ES: 'Spain',
  TH: 'Thailand',
  IR: 'Iran',
  KR: 'South Korea',
  ID: 'Indonesia',
  NO: 'Norway',
  VN: 'Vietnam',
  DK: 'Denmark',
  TR: 'Turkey',
  MY: 'Malaysia',
  CH: 'Switzerland',
  DZ: 'Algeria',
  EG: 'Egypt',
  SG: 'Singapore',
  'SG/TW': 'Singapore/Taiwan',
  KZ: 'Kazakhstan',
  PK: 'Pakistan',
  NG: 'Nigeria',
  MX: 'Mexico',
  CL: 'Chile',
  BY: 'Belarus',
  VE: 'Venezuela',
  AZ: 'Azerbaijan',
  AT: 'Austria',
  EC: 'Ecuador',
  EE: 'Estonia',
  ZA: 'South Africa',
  NL: 'Netherlands',
  BO: 'Bolivia',
  'FR/IT': 'France/Italy',
  BE: 'Belgium',
  UA: 'Ukraine',
  IQ: 'Iraq',
  PL: 'Poland',
  'CN/BR': 'China/Brazil',
  'TM/MC': 'Turkmenistan/Monaco',
  LA: 'Laos',
  PE: 'Peru',
  FI: 'Finland',
  BG: 'Bulgaria',
  TW: 'Taiwan',
  MA: 'Morocco',
  BD: 'Bangladesh',
  PH: 'Philippines',
  UNK: 'Unknown',
  JO: 'Jordan',
  'GR/SA': 'Greece/Saudi Arabia',
  CZ: 'Czech Republic',
  ET: 'Ethiopia',
  SI: 'Slovenia',
  LT: 'Lithuania',
  TN: 'Tunisia',
  SK: 'Slovakia',
  HU: 'Hungary',
  KW: 'Kuwait',
  RW: 'Rwanda',
  AO: 'Angola',
  CO: 'Colombia',
  KE: 'Kenya',
  MC: 'Monaco',
  VA: 'Vatican City',
  DJ: 'Djibouti',
  KP: 'North Korea',
  AM: 'Armenia',
  IE: 'Ireland',
  PT: 'Portugal',
  NZ: 'New Zealand'
}

export function countryToNameConversion(country: string): string {
  if (!(country in countryToName)) {
    return 'Unknown'
  }
  return countryToName[country as keyof typeof countryToName]
}
