on:
  workflow_run:
    workflows: ["Build the frontend", "Build the backend"]
    types:
      - completed
  
jobs:
  deploy:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      packages: read

    steps:
    - name: SSH into VPS
      uses: appleboy/ssh-action@71d43ea0f75a1f73c9b0e4608c059783968ad29c
      with:
        host: ${{ secrets.VPS_HOST }}
        port: ${{ secrets.VPS_PORT }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          echo 'Connected via SSH'
          cd /opt/docker/
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          docker compose pull
          docker compose up -d